version: "2.1"
services:
  rabbitmq:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mssqlpass
    volumes:
      - ./mssqldata:/var/opt/mssql
    ports:
      - 1433:1433